version: '3.8'
services:
  postgres:
    image: postgres:14.1
    restart: always
    environment:
      - POSTGRES_USER=prepverse
      - POSTGRES_PASSWORD=prepverse
      - POSTGRES_DB=prepverse
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
